# Generated by Django 5.2.14 on 2026-05-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0002_alter_encomienda_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encomienda',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
