# Generated by Django 6.0.4 on 2026-05-09 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0003_alter_encomienda_id'),
        ('envios', '0003_empleado_alter_encomienda_options_and_more'),
    ]

    operations = [
    ]
