# Generated by Codex on 2026-05-09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import envios.validators


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('envios', '0004_merge_20260508_2304'),
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encomienda',
            name='codigo',
            field=models.CharField(
                max_length=20,
                unique=True,
                validators=[envios.validators.validar_codigo_encomienda],
            ),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='costo_envio',
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='destinatario',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='envios_como_destinatario',
                to='clientes.cliente',
            ),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='estado',
            field=models.CharField(
                choices=[
                    ('PE', 'Pendiente'),
                    ('TR', 'En transito'),
                    ('DE', 'En destino'),
                    ('EN', 'Entregado'),
                    ('DV', 'Devuelto'),
                ],
                default='PE',
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='peso_kg',
            field=models.DecimalField(
                decimal_places=2,
                max_digits=8,
                validators=[
                    envios.validators.validar_peso_positivo,
                    django.core.validators.MinValueValidator(
                        0.01,
                        message='El peso minimo es 0.01 kg',
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='remitente',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='envios_como_remitente',
                to='clientes.cliente',
            ),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='ruta',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='encomiendas',
                to='rutas.ruta',
            ),
        ),
        migrations.AlterField(
            model_name='historialestado',
            name='estado_anterior',
            field=models.CharField(
                choices=[
                    ('PE', 'Pendiente'),
                    ('TR', 'En transito'),
                    ('DE', 'En destino'),
                    ('EN', 'Entregado'),
                    ('DV', 'Devuelto'),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name='historialestado',
            name='estado_nuevo',
            field=models.CharField(
                choices=[
                    ('PE', 'Pendiente'),
                    ('TR', 'En transito'),
                    ('DE', 'En destino'),
                    ('EN', 'Entregado'),
                    ('DV', 'Devuelto'),
                ],
                max_length=2,
            ),
        ),
    ]
